-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 21:28:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema message_dbo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `message_dbo` ;

-- -----------------------------------------------------
-- Schema message_dbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `message_dbo` ;
USE `message_dbo` ;

-- -----------------------------------------------------
-- Table `message_dbo`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message_dbo`.`message` ;

CREATE TABLE IF NOT EXISTS `message_dbo`.`message` (
  `message_id` INT NOT NULL,
  `identifier` VARCHAR(255) NULL,
  `sender_id` INT NULL,
  `sender` VARCHAR(255) NULL,
  `sent_time` TIMESTAMP NULL,
  `scope` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `message_type` VARCHAR(45) NULL,
  `source` VARCHAR(45) NULL,
  `cap_xml` TEXT NULL,
  PRIMARY KEY (`message_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
