-- MySQL Script generated by MySQL Workbench
-- Sat Jan 19 11:11:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cadg` ;

-- -----------------------------------------------------
-- Schema cadg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadg` ;
USE `cadg` ;

-- -----------------------------------------------------
-- Table `cadg`.`originator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadg`.`originator` ;

CREATE TABLE IF NOT EXISTS `cadg`.`originator` (
  `originator_id` INT NOT NULL,
  `originator_name` VARCHAR(45) NULL,
  `status` ENUM('ACTIVE', 'DISABLED') NULL,
  `agency` VARCHAR(45) NULL,
  PRIMARY KEY (`originator_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadg`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadg`.`message` ;

CREATE TABLE IF NOT EXISTS `cadg`.`message` (
  `message_id` INT NOT NULL,
  `identifier` VARCHAR(255) NULL,
  `originator_id` INT NULL,
  `message_type` ENUM('ACTUAL', 'EXERCISE', 'SYSTEM', 'TEST', 'DRAFT') NULL,
  `scope` ENUM('PUBLIC', 'RESTRICTED', 'PRIVATE') NULL,
  `status` ENUM('ACTIVE', 'CANCELED', 'EXPIRED') NULL,
  `urgency` ENUM('IMMEDIATE', 'EXPECTED', 'FUTURE', 'PAST', 'UNKNOWN') NULL,
  `severity` ENUM('EXTREME', 'SEVERE', 'MODERATE', 'MINOR', 'UNKNOWN') NULL,
  `sent_time` TIMESTAMP NULL,
  `cap_xml` TEXT NULL,
  PRIMARY KEY (`message_id`),
  CONSTRAINT `message_originator`
    FOREIGN KEY (`originator_id`)
    REFERENCES `cadg`.`originator` (`originator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `message_originator_idx` ON `cadg`.`message` (`originator_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `cadg`.`disseminator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadg`.`disseminator` ;

CREATE TABLE IF NOT EXISTS `cadg`.`disseminator` (
  `disseminator_id` INT NOT NULL,
  `disseminator_name` VARCHAR(45) NULL,
  `disseminator_type` ENUM('CMSP') NULL,
  `message_format` ENUM('CMAC') NULL,
  `ip` VARCHAR(45) NULL,
  `port` INT NULL,
  `status` ENUM('ACTIVE', 'DISABLED') NULL,
  PRIMARY KEY (`disseminator_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
